### ISSUE TITLE
First steps into Vue development

### ISSUE THREAD

**Issue by git-afsantos** [HAROS-framework/harosviz#2]
## Where to start reading code

The root of the project is `index.html`, which runs `src/main.ts`, which, in turn, imports `src/App.vue`. The first two do not really change all that often, after the initial setup. `App.vue` is the root Vue component that defines the page layout and loads all other sub-components.

## The App component

A `.vue` file typically contains 3 sections:

- `script` where all JavaScript / TypeScript related to this component goes;
- `template` where the rendered HTML goes;
- `style` where CSS style definitions go.

In the `template` section, this component defines a header and a main body. The header contains a few links to tabs/views within the application, and the body loads a different component depending on the selected view (functionality provided by the Vue router library).

```vue
<template>
  <header class="app-header">
    <h1>Stratis</h1>

    <nav class="app-nav">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/issues">Issues</RouterLink>
      <RouterLink to="/source">Source</RouterLink>
      <RouterLink to="/runtime">Runtime</RouterLink>
    </nav>
  </header>

  <div class="app-view">
    <RouterView />
  </div>
</template>
```

## Task 1

Navigate to `src/views/SourceView.vue`, where you may find the view corresponding to the **Source** tab.

## Task 2

In the `script`section of this file, create a new *string reference* - a `ref`, which is a Vue wrapper for a *reactive* variable. Reactive means that, whenever the inner value of this variable changes, all rendered HTML that reads from this variable will be updated on the fly, in the actual live app.

```vue
<script setup lang="ts">
import { ref } from 'vue'
const name = ref<string>('World')
</script>
```

## Task 3

Adapt the HTML text to read from this reactive variable.

```vue
<template>
  <div class="source">
    <h1>Hello, {{ name }}</h1>
  </div>
</template>
```

## Task 4

Save the file. Open a terminal within VS Code. Run the development server with `npm run dev` and open the `localhost` page on a web browser. Navigate to the Source tab to see your changes.

While the page is still open and the server is still running, change the `name` value from `World` to `HAROS`. Save the file and watch the web page update automatically due the development server live preview.

## Task 5

Add a new `ref<number>` named `count`, starting at zero.

```ts
const count = ref<number>(0)
```

Add a new paragraph that reads from this counter.

```html
<p>Click counter: {{ count }} times.</p>
```

## Task 6

Create a new function that increments the counter's value.

**Note:** when accessing a `ref` *within the `script` section of the file*, you need to append `.value` in order to read/write the actual value wrapped by the `ref`.

```ts
function increment(): void {
  count.value++
}
```

## Task 7

Add a button that calls this function when clicked. Since a click is a default HTML event, you can use the normal `onclick` attribute of the button, or Vue's shorthand syntax that also works for user-defined events in any component. Notice that, just like `ref`s, `function`s declared in `<script setup>` are also available in the `<template>` section.

```html
<button @click="increment">Click Me</button>
```

Save the file, and click the button a few times in the web browser to watch the text update with the current counter value.

## Conclusion

This is the basis for all dynamic content with Vue. The official documentation is comprehensive and mostly easy to understand.
All the main views, accessible from the `App.vue` dashboard, are under `src/views`. Sub-components used by these views are defined under `src/components`.

**Comment by andreami5280** [comment]
Good to go on first steps.
